---
- name: Install apt packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
  become: yes
  become_method: sudo
  with_items:
    - git
    - make
    - curl
    - software-properties-common
    - man-db
    - help2man
